version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=board-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./nest-board-app
      dockerfile: ./Dockerfile
    environment:
      - RDS_HOSTNAME=db
      - RDS_PORT=5432
      - RDS_DB_NAME=board-app
      - RDS_USERNAME=postgres
      - RDS_PASSWORD=postgres
    depends_on:
      - db
    ports:
      - "3000:3000"
    command:
      - bash
      - -c
      - |
        /app/wait-for-it.sh db:5432 -t 10
        npm run start:dev
    volumes:
      - ./nest-board-app/:/app/

volumes:
  postgres_data: null
